---
# tasks file for WorkerNode
# tasks file for WorkerNode

- name: "Installing Docker"
  package:
    name: docker
    state: present
- name: "Starting Docker Service"
  service:
    name: "docker"
    state: started
    enabled: yes
- name: "Configuring yum for kubectl,kubeadm,kubelet programs"
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: >-
      https://packages.cloud.google.com/yum/doc/yum-key.gpg
      https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    file: kubernetes
- name: "Installing kubelet,kubectl,kubeadm and iproute-tc"
  package:
    name: "{{ item }}"
    state: present
  loop:
  - kubelet
  - kubeadm
  - kubectl
  - iproute-tc
- name: "Starting kubelet program"
  service:
    name: "kubelet"
    state: started
    enabled: yes
- name: "Pulling all the required images"
  command: "kubeadm config images pull"
- name: "Changing the cgroup driver of docker to 'systemd'"
  copy:
    dest: "/etc/docker/daemon.json"
    src: "daemon.json"
- name: "Restarting Docker"
  service:
    name: "docker"
    state: restarted
    enabled: yes
- shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
- name: "Clearing Caches"
  shell: "echo '3' > /proc/sys/vm/drop_caches"
- name: "Copying k8s.conf file"
  copy:
    dest: "/etc/sysctl.d/k8s.conf"
    src: "k8s.conf"
- name: "Refreshing sysctl"
  shell: "sysctl --system"
