- name: "Launching Master Node"
  ec2:
    key_name: aws
    instance_type: t2.micro
    image: ami-047a51fa27710816e
    wait: true
    group: MultiNodeCluster
    count: 1
    vpc_subnet_id: subnet-e533d4d4
    assign_public_ip: yes
    region: us-east-1
    state: present
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    instance_tags:
      Name: MasterNode
  register: master_info
