- name: "Security Group for both Master and Worker Nodes"
  ec2_group:
    name: MultiNodeCluster
    description: "This SG allows allows all traffic"
    region: us-east-1
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    rules:
    - proto: all
      cidr_ip: 0.0.0.0/0
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0
